version: 2.1
jobs:
  style_check:
    docker:
      - image: node:16.16.0
    steps:
      - run:
          name: Lint Styles
          command: npm install && npm run lint
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
workflows:
  build_and_test:
    jobs:
      - style_check
      - build:
         requires:
          - style_check