version: 2.1
executors:
  node-16:
    docker:
      - image: gcbest/docker-cimg-pnpm
    # working_directory: /tmp

jobs:
  # pnpm:
  #   executor: node-16
  #   steps:
  #     - run: 
  #         name: Make workspace
  #         command: |
  #           mkdir -p workspace/pnpm
  #     - run:
  #         name: Install pnpm
  #         command: |
  #           curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
  #           pnpm config set store-dir /workspace/pnpm/.pnpm-store
  #     - persist_to_workspace:
  #         root: workspace
  #         paths: 
  #           - pnpm
 
  lint:
    executor: node-16
    steps:
      - checkout
      # - attach_workspace:
      #     at: /tmp/workspace
      # - run: cd workspace && ls
      - restore_cache:
          key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Lint Styles 
          command: |
            pnpm install
            pnpx eslint . --ext .js,.jsx,.ts,.tsx
      - save_cache:
          key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
          paths: 
            - node_modules
  build:
    executor: node-16
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install packages
          command: | 
            pnpm install
      - save_cache:
          key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
          paths: 
            - ./node_modules
      - restore_cache:
          key: next-build-deps-{{ checksum "pnpm-lock.yaml" }}
      - run: 
          name: Build App
          command:
            pnpm build
      - save_cache:
          key: next-build-deps-{{ checksum "pnpm-lock.yaml" }}
          paths: 
            - ./.next/cache
  test_unit_integration:
    executor: node-16
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
      - run: 
          name: Install Packages
          command: |
              pnpm install
      - save_cache:
          key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
          paths: 
            - node_modules
      - run:
          name: Unit & Integration
          command: pnpm test
  test_e2e:
    docker:
      - image: mcr.microsoft.com/playwright:v1.23.1-focal
    environment:
        NODE_ENV: development # Needed if playwright is in `devDependencies`
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
      - run: 
          name: Install Packages
          command: |
              pnpm install
      - save_cache:
          key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
          paths: 
            - node_modules
      - run:
          name: End to End
          command:
            pnpm run test:e2e
            
workflows:
  lint_build_test:
    jobs:
      # - pnpm
      - lint
        #  requires:
        #    - pnpm
      - build:
         requires:
          - lint
      - test_unit_integration:
          requires:
            - build
      - test_e2e:
          requires:
            - build