version: 2.1
jobs:
  style_check:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run:
          name: Lint Styles 
          command: npm install -g pnpm && pnpm install && pnpx eslint . --ext .js,.jsx,.ts,.tsx
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
workflows:
  lint_build_test:
    jobs:
      - style_check
      - build:
         requires:
          - style_check