version: 2.1
executors:
  node-16:
    docker:
      - image: gcbest/cimg-pnpm
restore_cache: &restore_cache
  restore_cache:
    key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
save_cache: &save_cache
  save_cache:
    key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
    paths: 
      - node_modules

jobs:
  lint:
    executor: node-16
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Lint Styles 
          command: pnpx eslint . --ext .js,.jsx,.ts,.tsx
      - *save_cache
  test_unit_integration:
    executor: node-16
    steps:
      - checkout
      - *restore_cache
      - run: 
          name: Install Packages
          command: pnpm install
      - *save_cache
      - run:
          name: Unit & Integration
          command: pnpm test
  test_e2e:
    docker:
      - image: mcr.microsoft.com/playwright:v1.23.1-focal
    environment:
        NODE_ENV: development # Needed if playwright is in `devDependencies`
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-deps-{{ checksum "pnpm-lock.yaml" }}
      - run: 
          name: Install Packages
          command: |
              npx playwright install
              npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "pnpm-lock.yaml" }}
          paths: 
            - node_modules
      - run:
          name: End to End
          command: npm run test:e2e
  deploy_staging:
    executor: node-16
    steps:
      - checkout
      - run:
          name: Install Railway
          command: npm i -g @railway/cli
      - restore_cache:
          key: next-build-deps-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Deploy
          command: RAILWAY_TOKEN=${RAILWAY_TOKEN_STAGING} railway up
      - save_cache:
          key: next-build-deps-{{ checksum "pnpm-lock.yaml" }}
          paths: 
            - ./.next/cache
  deploy_production:
    executor: node-16
    steps:
      - checkout
      - run:
          name: Install Railway
          command: npm i -g @railway/cli
      - restore_cache:
          key: next-build-deps-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Deploy
          command: RAILWAY_TOKEN=${RAILWAY_TOKEN_PRODUCTION} railway up
      - save_cache:
          key: next-build-deps-{{ checksum "pnpm-lock.yaml" }}
          paths: 
            - ./.next/cache

workflows:
  lint_test_deploy:
    jobs:
      - lint
      - test_unit_integration:
          requires:
            - lint
      - test_e2e:
          requires:
            - lint
      - deploy_staging:
          requires:
            - test_e2e
            - test_unit_integration
      - deploy_production:
          requires:
            - deploy_staging
          filters:
            branches:
              only:
                - main